name: Deploy FastAPI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted 

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python and Virtual Environment
      run: |
        # Navigate to the project directory
        cd /home/pomona/fast-runner/_work/pharmassist_api/pharmassist_api

        # Create a virtual environment with copies of dependencies
        python -m venv venv
        # Activate the virtual environment
        source venv/bin/activate

        # Upgrade pip, setuptools, and wheel
        pip install --upgrade pip setuptools wheel

        # Install dependencies
        pip install -r requirements.txt
        pip install "fastapi[standard]"

    - name: Start FastAPI
      run: |
        cd /home/pomona/fast-runner/_work/pharmassist_api/pharmassist_api/api
        source ../venv/bin/activate
        fastapi run main.py --host 0.0.0.0 --port 8000 &
