name: Deploy FastAPI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted 

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4

        
    - name: Install Dependencies
      run: |
        cd /home/pomosa/actions-runner/_work/pharmassist_api/pharmassist_api
        python -m pip install --upgrade pip setuptools wheel
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt

    # - name: Restart FastAPI Service
    #   run: |
    #     sudo systemctl restart fastapi.service