name: Deploy FastAPI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted 

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'  # Use a stable Python version

    - name: Set up Python and Virtual Environment
      run: |
        # Ensure Python 3.11 is available
        python3 --version

        # Navigate to the project directory
        cd /home/pomona/fast-runner/_work/pharmassist_api/pharmassist_api

        # Create a virtual environment with the explicit Python path
        python3.11 -m venv venv

        # Activate the virtual environment
        source venv/bin/activate

        # Export library path
        export LD_LIBRARY_PATH=$(python3.11 -c 'import sysconfig; print(sysconfig.get_config_var("LIBDIR"))'):$LD_LIBRARY_PATH

        # Upgrade pip, setuptools, and wheel
        pip install --upgrade pip setuptools wheel

        # Install dependencies
        pip install -r requirements.txt
        pip install "fastapi[standard]"

    - name: Activate Venv
      run: |
        cd /home/pomona/fast-runner/_work/pharmassist_api/pharmassist_api/api
        source ../venv/bin/activate
    - name: Start FASTAPI
      run: |
        cd /home/pomona
        ./run_fastapi.sh
