name: Deploy FastAPI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted 

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'  # Use a stable Python version

    - name: Install Dependencies
      run: |
        # Navigate to the project directory
        cd /home/pomona/fast-runner/_work/pharmassist_api/pharmassist_api
        
        # Upgrade pip, setuptools, and wheel to the latest versions
        pip install --upgrade pip setuptools wheel
        
        # Install the dependencies from requirements.txt
        pip install -r requirements.txt
        
        # Install FastAPI standard dependencies (if needed)
        pip install "fastapi[standard]"
